linux-arm ready

diff --git a/Dockerfile.linux-arm b/Dockerfile.linux-arm
--- a/Dockerfile.linux-arm
+++ b/Dockerfile.linux-arm
@@ -1,26 +1,49 @@
 FROM nodered/node-red-docker:rpi-v8
 USER root
-ENV HOST_NAME mydiskstation
+ENV HOST_NAME myrpi_hostname
+ENV GOSU_VERSION 1.10
 
 # Install required packages
-RUN apk add --no-cache git python make g++ avahi-compat-libdns_sd avahi-dev dbus su-exec
+RUN apt-get update -y && apt-get install -y --no-install-recommends python make g++ avahi-daemon avahi-discover libnss-mdns libavahi-compat-libdnssd-dev
 
-# Insert HOST_NAME into avahi-daemon.conf
-#RUN sed -i "s/#enable-dbus=yes/enable-dbus=yes/g" /etc/avahi/avahi-daemon.conf && sed -i "s/.*host-name.*/host-name='$HOST_NAME'/" /etc/avahi/avahi-daemon.conf
-RUN mkdir -p /var/run/dbus && mkdir -p /var/run/avahi-daemon
-RUN chown messagebus:messagebus /var/run/dbus && chown avahi:avahi /var/run/avahi-daemon && dbus-uuidgen --ensure
+# Install gosu via https://github.com/tianon/gosu/blob/master/INSTALL.md
+RUN set -ex; \
+	\
+	fetchDeps=' \
+		ca-certificates \
+		wget \
+	'; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends $fetchDeps; \
+	rm -rf /var/lib/apt/lists/*; \
+	\
+	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+	\
+# verify the signature
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+	rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+	\
+	chmod +x /usr/local/bin/gosu; \
+# verify that the binary works
+	gosu nobody true; \
+	\
+	apt-get purge -y --auto-remove $fetchDeps
 
-RUN chown root:node-red /sbin/su-exec && chmod +s /sbin/su-exec
+RUN chown root:node-red /usr/local/bin/gosu && chmod +s /usr/local/bin/gosu && \
+    mkdir -p /var/run/dbus && mkdir -p /var/run/avahi-daemon && \
+    chown messagebus:messagebus /var/run/dbus && chown avahi:avahi /var/run/avahi-daemon && dbus-uuidgen --ensure
 
+# Install node-red-contrib-homekit
 USER node-red
 #RUN npm install node-red-contrib-homekit
 RUN npm install @boneskull/node-red-contrib-homekit
 
-# Clean up
-RUN su-exec root apk del git python make g++ && \
-    su-exec root rm -rf /var/cache/apk/*
-    
-COPY entrypoint.sh /usr/src/node-red
-RUN su-exec root chmod 755 /usr/src/node-red/entrypoint.sh
+# Cleanup Todo
 
-ENTRYPOINT /usr/src/node-red/entrypoint.sh
+COPY entrypoint.linux-arm /usr/src/node-red/entrypoint.sh
+RUN gosu root chmod 755 /usr/src/node-red/entrypoint.sh
+ENTRYPOINT ["/usr/src/node-red/entrypoint.sh"]
